version: '3.1'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 1433:1433
    environment:
      - MSSQL_SA_PASSWORD=password1234$
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer